backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('bank.urls')),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
]

backend/bank/urls.py
from django.urls import path

from .views import create_bank, bank_info, index, create_manager, create_client, create_accountant

app_name = 'bank'

urlpatterns = [
    path("bank/<int:bank_id>/", bank_info, name='bank_info'),
    path("", index, name='index'),
    path("create_bank/", create_bank, name='create_bank'),
    path("create_accountant/", create_accountant, name='create_accountant'),
    # path("accountant/", accountant, name='accounts'),
    path("create_manager/", create_manager, name='create_manager'),
    path("create_client/", create_client, name='create_client'),
]

backend/bank/models.py
from django.db import models

from users.models import CustomUser


class Bank(models.Model):
    name = models.CharField(verbose_name='Name of the bank', max_length=200)
    min_client_deposit = models.IntegerField(verbose_name='Min client deposit')
    director = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='banks')

    def __str__(self):
        return self.name


class Director(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='director')
    bank = models.ForeignKey(to=Bank, on_delete=models.CASCADE, related_name='directors', null=True, blank=True)


class Accountant(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='accountant')
    salary = models.IntegerField(verbose_name='Salary', default=0)
    bank = models.ForeignKey(to=Bank, on_delete=models.CASCADE, related_name='accountants', null=True, blank=True)


class Manager(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='manager')
    salary = models.IntegerField(verbose_name='Salary', default=0)
    accountant = models.ForeignKey(Accountant, verbose_name='Accountant of the manager',
                                   on_delete=models.CASCADE, related_name='managers')
    bank = models.ForeignKey(to=Bank, on_delete=models.CASCADE, related_name='managers', null=True, blank=True)


class Client(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='client')
    money = models.IntegerField(verbose_name='Salary', default=0)
    manager = models.ForeignKey(Manager, verbose_name='Accountant of the manager',
                                on_delete=models.CASCADE, related_name='clients')
    bank = models.ForeignKey(to=Bank, on_delete=models.CASCADE, related_name='clients', null=True, blank=True)

backend/bank/forms.py
from django import forms
from bank.models import Bank
from bank.models import Manager, Client, Accountant
#
#
class BankForm(forms.ModelForm):
    class Meta:
        model = Bank
        fields = ('name', 'min_client_deposit')
#
#
# class AccountantForm(forms.ModelForm):
#     class Meta:
#         model = Accountant
#         fields = ('name', 'bank', 'salary')
#
#


class AccountantForm(forms.Form):
    accountant = forms.ModelChoiceField(queryset=Accountant.objects.all(), label='Accountant')
    salary = forms.IntegerField(min_value=100, label='Salary')


class ManagerForm(forms.Form):
    manager = forms.ModelChoiceField(queryset=Manager.objects.all(), label='Manager')
    accountant = forms.ModelChoiceField(queryset=Accountant.objects.all(), label='His Accountant')
    salary = forms.IntegerField(min_value=100, label='Salary')


class ClientsForm(forms.ModelForm):
    manager = forms.ModelChoiceField(queryset=Manager.objects.all(), label='His Manager')
    client = forms.ModelChoiceField(queryset=Client.objects.all(), label='Client')
    money = forms.IntegerField(min_value=100, label='Deposit')

backend/bank/views.py
from django.shortcuts import render, redirect
from bank.models import Bank, Accountant, Director, Client, Manager
from .forms import BankForm, AccountantForm, ManagerForm, ClientsForm
from django.contrib.auth.decorators import login_required
from users.models import CustomUser
from random import choice


# CBV - class based views
# FBV - function based views

# @login_required
# def banks(request):
#     banks = Bank.objects.all()
#     return render(request, "bank/banks.html", context={'banks': banks})
#
#
# @login_required
# def accountant(request):
#     accounts = Accountant.objects.all()
#     return render(request, "bank/accounts.html", context={'account': accounts})
#
#
@login_required
def create_accountant(request):
    if request.user.role != CustomUser.Roles.DIRECTOR:
        return redirect('bank:index')
    form = AccountantForm()
    if request.method == 'GET':
        return render(request, "bank/create_accountant.html", context={'form': form})
    elif request.method == 'POST':
        form = AccountantForm(request.POST)
        if form.is_valid():
            accountant = form.cleaned_data['accountant']
            accountant.salary = form.cleaned_data['salary']
            accountant.bank = request.user.director.bank
            accountant.save()
            return redirect('bank:index')
    return render(request, "bank/create_accountant.html", context={'form': form})
# Create Manager


# director
@login_required
def create_bank(request):
    if request.user.role != CustomUser.Roles.DIRECTOR:
        return redirect('bank:index')
    form = BankForm()
    if request.method == 'GET':
        return render(request, "bank/create_bank.html", context={'form': form})
    elif request.method == 'POST':
        form = BankForm(request.POST)
        if form.is_valid():
            bank = form.save(commit=False)
            director = request.user.director
            bank.director = director
            director.bank = bank
            bank.save()
            return redirect('bank:bank_info', bank.id)
    return render(request, "bank/create_bank.html", context={'form': form})



# Check
# accountant and director
def create_manager(request):
    if request.user.role != CustomUser.Roles.DIRECTOR:
        return redirect('login')
    form = ManagerForm()
    if request.method == 'GET':
        return render(request, "bank/create_manager.html", context={'form': form})
    elif request.method == 'POST':
        form = ManagerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bank:manager')
    return render(request, "bank/create_manager.html", context={'form': form})



# Check
# director accountant manager
def create_client(request):
    if request.user.role != CustomUser.Roles.DIRECTOR:
        return redirect('login')
    form = ClientsForm()
    if request.method == 'GET':
        return render(request, "bank/create_client.html", context={'form': form})
    elif request.method == 'POST':
        form = ClientsForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.bank = request.user.bank
            if client.money < client.bank.min_client_deposit:
                return render(request, "bank/create_client.html", context={'form': form})
            else:
                client.manager = choice(client.bank.managers.all())
                client.save()
                return redirect("bank:bank_info", client.bank.id)


# all
def bank_info(request, bank_id):
    bank = Bank.objects.get(pk=bank_id)
    if Director.objects.filter(user=request.user, bank=bank).exists():
        return render(request, "bank/bank.html", context={'bank': bank})
    if Manager.objects.filter(user=request.user, bank=bank).exists():
        return render(request, "bank/bank.html", context={'bank': bank})
    if Accountant.objects.filter(user=request.user, bank=bank).exists():
        return render(request, "bank/bank.html", context={'bank': bank})
    if Client.objects.filter(user=request.user, bank=bank).exists():
        return render(request, "bank/bank.html", context={'bank': bank})
    return redirect('bank:index')



# all
def profile(request):
    pass



def index(request):
    return render(request, "bank/index.html")

backend/templates/bank/accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for acc in account %}
        <p>{{acc.name}}</p>
    {% endfor %}
</body>
</html>

backend/templates/bank/bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Banks</h1>>
    <p>
    <h3> {{ bank.name }} </h3>
    <p>Минимальный депозит клиента - {{ bank.min_client_deposit }}</p>
    <p>Бухгалтеры банка </p>
    {% for acc in bank.accountants.all %}
        {{ acc.user.username }}
    {% endfor %}
    </p>
</body>
</html>

backend/templates/bank/create_accountant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'bank:create_accountant' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>

</form>
</body>
</html>

backend/templates/bank/create_bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'bank:create_bank' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>

</form>
</body>
</html>

backend/templates/bank/create_client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'bank:create_client' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>

</form>
</body>
</html>

backend/templates/bank/create_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'bank:create_manager' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>

</form>
</body>
</html>

backend/templates/bank/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'bank:create_client'%}">Create client</a>
    <a href="{% url 'bank:create_bank'%}">create_bank</a>
    <a href="{% url 'bank:create_manager'%}">create_manager</a>
    <a href="{% url 'bank:create_accountant'%}">create_accountant</a>
</body>
</html>